// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_4rWM1xryS11EZ9DgL4Y4exTcnz5TGCY',
    appId: '1:992925327648:web:3b6dae5ac4fee70634b745',
    messagingSenderId: '992925327648',
    projectId: 'driving-school-ad326',
    authDomain: 'driving-school-ad326.firebaseapp.com',
    storageBucket: 'driving-school-ad326.appspot.com',
    measurementId: 'G-MV4Q517ZT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAWuMrxxhtnlO1W2gpGMM_7F9OiOqpyss',
    appId: '1:992925327648:android:be9d3dc4426fe49d34b745',
    messagingSenderId: '992925327648',
    projectId: 'driving-school-ad326',
    storageBucket: 'driving-school-ad326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGdgir8cKlHM06b-wxsg_uxWRxBZOkcks',
    appId: '1:992925327648:ios:4642cc50527efe7934b745',
    messagingSenderId: '992925327648',
    projectId: 'driving-school-ad326',
    storageBucket: 'driving-school-ad326.appspot.com',
    iosBundleId: 'com.example.drivingSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGdgir8cKlHM06b-wxsg_uxWRxBZOkcks',
    appId: '1:992925327648:ios:4642cc50527efe7934b745',
    messagingSenderId: '992925327648',
    projectId: 'driving-school-ad326',
    storageBucket: 'driving-school-ad326.appspot.com',
    iosBundleId: 'com.example.drivingSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8rwtkvWtCw6wiVLdrLbiNS8f_5tC30Vg',
    appId: '1:992925327648:web:66ded6fd021a706834b745',
    messagingSenderId: '992925327648',
    projectId: 'driving-school-ad326',
    authDomain: 'driving-school-ad326.firebaseapp.com',
    storageBucket: 'driving-school-ad326.appspot.com',
    measurementId: 'G-2GXGTCET84',
  );

}